# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

version: '0.2'
env:
  shell: bash
  variables:
    NV_USERNAME: <nv_controller_user_name>
    NV_CONTROLLER: <nv_controller_api_url>
    OCIREPO: <container_image_repo_name>
    OCIREPOURI: <container_image_repo_url>
    OCINAME: <application_name>
  secrets-manager:
    NV_PASSWORD: <aws_secrets_name>  # Secrets must be in same region as AWS CodeBuild Project
phases:
  install:
    on-failure: ABORT
    commands:
      - set -e
      - set -o pipefail
      - export COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -b -8)  # 8 digit git hash, used as image label/tag
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $OCIREPOURI  # Adjust AWS region or move into variable
      - chmod +x $CODEBUILD_SRC_DIR_buildscripts/*.sh
  pre_build:
    on-failure: ABORT
    commands:
      - 'docker run -d -p 5000:5000 --name registry registry:2'  # Workaround, required till https://github.com/neuvector/neuvector/issues/1423 is solved.
  build:
    on-failure: ABORT
    commands:
      - |
        set -e
        docker build -t localhost:5000/$OCINAME:$COMMIT_ID -t $OCIREPO:$COMMIT_ID -t $OCIREPOURI:$COMMIT_ID $CODEBUILD_SRC_DIR
        docker push localhost:5000/$OCINAME:$COMMIT_ID
        docker images
        docker inspect localhost:5000/$OCINAME:$COMMIT_ID
        $CODEBUILD_SRC_DIR_buildscripts/scan.sh localhost:5000/$OCINAME $COMMIT_ID $CODEBUILD_SRC_DIR $NV_USERNAME $NV_PASSWORD $NV_CONTROLLER
  post_build:
    on-failure: ABORT
    commands:
      - 'docker tag $OCIREPOURI:$COMMIT_ID $OCIREPOURI:latest'
      - 'docker push $OCIREPOURI:$COMMIT_ID'
      - 'docker push $OCIREPOURI:latest'
artifacts:
  files:
    - scan_result.json